from pathlib import Path
from pydantic import Field, BaseModel
from script2runner import CLI
from typing import List, Literal, Dict, ClassVar, Annotated

from dafn.runner_helper import get_file_pattern_from_suffix_list, check_output_paths

class Args(CLI):
    """
        - Goal: Creates analysis data of the recording. 
        - Technique: Uses spike interface sorting analyzer and custom tools. 
        - Formats: Input and output formats are in the .zarr formats generated by spike interface.
    """
    # recording_path: Annotated[Path, Field(
    #     description="Path to the folder containing the (usually preprocessed) recording",
    #     examples=["/media/t4user/data1/Data/SpikeSorting/...si.zarr"], 
    #     json_schema_extra=dict(pattern=get_file_pattern_from_suffix_list(start_path_patterns, [".si.zarr"]))
    # )]
    xarray_analyzer_path: Annotated[Path, Field(
        description="Path to the folder containing the recording analyzer created from the sorting and recording",
        default="/media/filer2/T4b/...xr.zarr", 
        json_schema_extra=dict(pattern=get_file_pattern_from_suffix_list([".xr.zarr"]))
    )]
    output_path: Annotated[Path, Field(
        default="/media/filer2/T4b/Temporary/....", 
        description="Location of the output folder containing the figures", 
        json_schema_extra=dict(pattern=get_file_pattern_from_suffix_list([]))
    )]
    allow_output_overwrite: bool = Field(default=False, description="If yes, erases the outputs if they exists before starting computation")
    _run_info: ClassVar = dict(gpu=False)
    
args = Args()
import xarray as xr, tqdm
from dafn.spike_sorting_visualization import mk_plot

with check_output_paths(args.output_path, args.allow_output_overwrite) as output_path:
    analysis_data = xr.open_zarr(args.xarray_analyzer_path).compute()
    print(analysis_data)
    for unit in tqdm.tqdm(analysis_data["unit"].to_numpy()[::-1]):
        try:
            html = mk_plot(analysis_data, unit)
            output_path.mkdir(exist_ok=True)
            with (output_path / f"unit_{unit}.html").open("w") as f:
                f.write(html) 
        except Exception as e:
            print(f"Error for unit {unit}. Error is {e}")
            raise


