from pathlib import Path
from pydantic import Field, BaseModel
from script2runner import CLI
from typing import List, Literal, Dict, ClassVar, Annotated

from dafn.runner_helper import get_file_pattern_from_suffix_list, check_output_paths
    
class Args(CLI):
    """
        - Goal: Creates analysis data of the recording. 
        - Technique: Uses spike interface sorting analyzer and custom tools. 
        - Formats: Input and output formats are in the .zarr formats generated by spike interface.
    """
    recording_path: Annotated[Path, Field(
        description="Path to the folder containing the (usually preprocessed) recording",
        default="/media/t4user/data1/Data/SpikeSorting/...si.zarr", 
        json_schema_extra=dict(pattern=get_file_pattern_from_suffix_list([".si.zarr"]))
    )]
    spikeinterface_analyzer_path: Annotated[Path, Field(
        default="/media/filer2/T4b/Temporary/....si.zarr", 
        description="Location of the analyzer", 
        json_schema_extra=dict(pattern=get_file_pattern_from_suffix_list([".si.zarr"]))
    )]
    output_path: Annotated[Path, Field(
        default="/media/filer2/T4b/Temporary/....xr.zarr", 
        description="Location of the output xarray data for plotting", 
        json_schema_extra=dict(pattern=get_file_pattern_from_suffix_list([".xr.zarr"]))
    )]

    allow_output_overwrite: bool = Field(default=False, description="If yes, erases the outputs if they exists before starting computation")
    _run_info: ClassVar = dict(conda_env="ss", gpu=False, memory=10)
    
args = Args()

import spikeinterface as si
from dafn.spike_sorting import xarray_sorting_analysis_data


with check_output_paths(args.output_path, args.allow_output_overwrite) as output_path:
    analyzer: si.SortingAnalyzer = si.load(args.spikeinterface_analyzer_path)
    rec: si.BaseRecording = si.load(args.recording_path)
    print(analyzer)
    print(rec)
    res_xr = xarray_sorting_analysis_data(analyzer, analyzer.sorting, rec, 30, 50, 101)
    print(res_xr)
    res_xr.to_zarr(output_path)



 
